### ISSUE TITLE
OnDeserializedAttribute support

### ISSUE THREAD

**Issue by rumcgit** [bridgedotnet/Bridge.Newtonsoft.Json#96]
Hello, Great Guys! 
I'm really excited to see such a steady support of JSON.NET for Bridge.
It would be extremely cool if you add OnDeserializedAttribute support. 
Assure you, it will help many existing projects!

Thank you!

## See Also

* https://github.com/bridgedotnet/Bridge/issues/2275

**Comment by geoffreymcgill** [comment]
Hi @rumcgit – Thanks for the reminder. We will investigate and try to get ** OnDeserializedAttribute** working for the next release. I was just looking at this as well.

**Comment by rumcgit** [comment]
Impressive! Thanks

**Comment by fabriciomurta** [comment]
Merged! This will be released on the next Bridge.Newtonsoft.Json version released. Currently, v1.7.1, but that can change until the version is actually published (depending on what changes within). So refer to the issue's milestone to see in which package vesion this issue is set to be published, as that will be updated in time.
